### ISSUE TITLE
ConcurrentModificationException when setting BlockData within the world generator

### ISSUE THREAD

**Issue by lorenzop** [PoiXson/pxnBackrooms-mirror#10]
exception caused by setting block data on slabs and stairs in world generators

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData.toNMS(CraftBlockData.java:181)
	at org.bukkit.craftbukkit.v1_19_R3.block.data.CraftBlockData.set(CraftBlockData.java:108)
	at org.bukkit.craftbukkit.v1_19_R3.block.impl.CraftStairs.setHalf(CraftStairs.java:41)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.utils.BlockUtils.ApplyBlockSpecial(BlockUtils.java:51)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.setSpecial(BlockPlotter.java:166)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.setType(BlockPlotter.java:154)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.run(BlockPlotter.java:139)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.run(BlockPlotter.java:118)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.run(BlockPlotter.java:118)
	at pxnCommonPluginMC-4.0.31.jar//com.poixson.commonmc.tools.plotter.BlockPlotter.run(BlockPlotter.java:105)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.gens.Gen_771.generatePillar(Gen_771.java:505)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.gens.Gen_771.generatePillars(Gen_771.java:340)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.gens.Gen_771.generateRoad(Gen_771.java:226)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.gens.Gen_771.generate(Gen_771.java:92)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.worlds.Level_771.generate(Level_771.java:149)
	at pxnBackrooms-0.1.5.jar//com.poixson.backrooms.BackroomsLevel.generateSurface(BackroomsLevel.java:139)
	at org.bukkit.craftbukkit.v1_19_R3.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:145)
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:150)
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:374)
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:305)
	at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83)
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351)
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118)
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274)
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50)

**Comment by lorenzop** [comment]
unknown cause, seems to be fixed by wrapping in a synchronized block
