### ISSUE TITLE
cannot use non-rotatable blocks for hotel hall walls

### ISSUE THREAD

**Issue by lorenzop** [PoiXson/pxnBackrooms-mirror#11]
exceptions are thrown when using a block like Hall-Wall: RED_WOOL

```
[02:05:01] [Tuinity Chunk System Worker #0/ERROR]: [ChunkTaskScheduler] Chunk system error at chunk (4,6), holder: NewChunkHolder{world=level0, chunkX=4, chunkZ=6, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=net.minecraft.world.level.chunk.ProtoChunk,status=minecraft:carvers}, currentGenStatus=minecraft:carvers, requestedGenStatus=minecraft:initialize_light, generationTask=ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask, for world: level0, chunk: (4,6), hashcode: 848738970, priority: COMPLETING, status: minecraft:features, scheduled: true}, generationTaskStatus=minecraft:features, priority=NORMAL, priorityLocked=false, neighbourRequestedPriority=BLOCKING, effective_priority=BLOCKING, oldTicketLevel=34, currentTicketLevel=34, totalNeighboursUsingThisChunk=8, fullNeighbourChunksLoadedBitset=0, chunkStatusRaw=0, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}, exception:
java.lang.Throwable: java.lang.IllegalArgumentException: Could not parse data: minecraft:red_wool[axis=y]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:276) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1700) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete0(ChunkProgressionTask.java:95) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete(ChunkProgressionTask.java:75) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:105) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.queue.RadiusAwarePrioritisedExecutor$Task.run(RadiusAwarePrioritisedExecutor.java:467) ~[paper-1.20.2.jar:git-Paper-318]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.2.jar:git-Paper-318]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.2.jar:git-Paper-318]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.2.jar:git-Paper-318]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.2.jar:git-Paper-318]
Caused by: java.lang.IllegalArgumentException: Could not parse data: minecraft:red_wool[axis=y]
	at org.bukkit.craftbukkit.v1_20_R2.block.data.CraftBlockData.createNewData(CraftBlockData.java:583) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:558) ~[paper-1.20.2.jar:git-Paper-318]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R2.block.data.CraftBlockData.newData(CraftBlockData.java:558) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.createBlockData(CraftServer.java:2790) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:[240](https://mclo.gs/1BVZC2u#L240)1) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at com.poixson.tools.plotter.BlockPlotter.type(BlockPlotter.java:158) ~[pxnPluginLib-4.0.46-SNAPSHOT.jar:?]
	at com.poixson.backrooms.gens.hotel.HotelRoomGuest.build(HotelRoomGuest.java:65) ~[pxnBackrooms-0.1.18-SNAPSHOT.jar:?]
	at com.poixson.backrooms.gens.Pop_005.buildHotelRooms(Pop_005.java:225) ~[pxnBackrooms-0.1.18-SNAPSHOT.jar:?]
	at com.poixson.backrooms.gens.Pop_005.populate(Pop_005.java:50) ~[pxnBackrooms-0.1.18-SNAPSHOT.jar:?]
	at com.poixson.backrooms.BackroomsLevel$PopulatorManager.populate(BackroomsLevel.java:82) ~[pxnBackrooms-0.1.18-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:490) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:301) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$11(ChunkStatus.java:127) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:342) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:259) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:86) ~[paper-1.20.2.jar:git-Paper-318]
	... 5 more
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:red_wool does not have property 'axis' at position 19: ...:red_wool[<--[HERE]
```

**Comment by lorenzop** [comment]
can fix this by adding new lines to the config

Hall-Wall-NS: minecraft:stripped_spruce_wood[axis=x]
Hall-Wall-EW: minecraft:stripped_spruce_wood[axis=z]

**Comment by lorenzop** [comment]
finished this. can set the top and bottom wall types and the center fill, as well as the door border/frame sides and top
